// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateInput struct {
	Name       string  `json:"name"`
	Surname    string  `json:"surname"`
	Patronymic *string `json:"patronymic,omitempty"`
}

type FilterInput struct {
	Name       *string  `json:"name,omitempty"`
	Surname    *string  `json:"surname,omitempty"`
	Patronymic *string  `json:"patronymic,omitempty"`
	Age        *int     `json:"age,omitempty"`
	AgeSort    *string  `json:"ageSort,omitempty"`
	Gender     []string `json:"gender,omitempty"`
	Country    []string `json:"country,omitempty"`
}

type GetInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type SortInput struct {
	SortBy    *string `json:"sortBy,omitempty"`
	SortOrder *string `json:"sortOrder,omitempty"`
}

type UpdateInput struct {
	ID         int     `json:"id"`
	Name       string  `json:"name"`
	Surname    string  `json:"surname"`
	Patronymic *string `json:"patronymic,omitempty"`
	Age        int     `json:"age"`
	Country    string  `json:"country"`
	Gender     string  `json:"gender"`
}

type User struct {
	ID         int     `json:"id"`
	Name       string  `json:"name"`
	Surname    string  `json:"surname"`
	Patronymic *string `json:"patronymic,omitempty"`
	Age        *int    `json:"age,omitempty"`
	Gender     *string `json:"gender,omitempty"`
	Country    *string `json:"country,omitempty"`
}
